services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "5005:8080" 
  uwsgi:
    build:
      context: ./uwsgi
      dockerfile: Dockerfile
    ports:
      - "5050:80" 